sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: root
  alioss:
    endpoint: oss-cn-guangzhou.aliyuncs.com
    access-key-id: ${OSS_ACCESS_KEY_ID}
    access-key-secret: ${OSS_ACCESS_KEY_SECRET}
    bucket-name: xingchen-web
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 0
  wechat:
    appid: wx85d383842a45a880
    secret: 0b8bbea9dc858e56599b30f40e80eaa0
